services:
  chess-app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true