services:
  chess-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LLAMA_SERVER_URL=http://llama_server:8080/v1/chat/completions
    container_name: chess-app
    hostname: chess-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - proxy_net
      - llm_net

networks:
  proxy_net:
    external: true
  llm_net:
    external: true